//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureSGADBComasur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosTable
    {
        public int IdPermiso { get; set; }
        public string NombrePermiso { get; set; }
        public int NumerodePermiso { get; set; }
    }
}
